### ISSUE TITLE
API key not in URI

### ISSUE THREAD

**Issue by dameunmordisco** [revett/youtube-comments#8]
There is an issue at assigning the API key when it makes de url at the API func, it can't find the value of key in it.

It can be solved by changing the line 119 

 `queryParams.Add("key", key)` 
to
`queryParams.Add("key", a.key)`

and sending the key value directly to the NewAPI func

**Comment by revett** [comment]
@dameunmordisco Thanks - could you add a PR to fix this please?

**Comment by revett** [comment]
@dameunmordisco This is all fixed. Closing issue.
